services:
    app:
        build:
            context: ./docker/php
        container_name: crm_php
        volumes:
            - .:/var/www/html
        networks:
            - app-network
        depends_on:
            - db

    web:
        image: nginx:1.25
        container_name: crm_nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app-network

    db:
        image: mysql:8.0
        container_name: crm_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"
        networks:
            - app-network
        volumes:
            - db_data:/var/lib/mysql

    node:
        image: node:20
        container_name: crm_node
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
        ports:
            - "5173:5173"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    db_data:
